[package]
name = "vinyl_collection"
version = "0.1.0"
authors = ["Kel Cecil <kelcecil@praisechaos.com>"]

[dependencies]
pencil = "0.2.1"
diesel = "0.6.1"
diesel_codegen = { version = "0.6.1", default-features = false, features = ["nightly", "postgres"] }
dotenv = "0.8.0"
dotenv_macros = "0.8.0"
